Pal 1034 add gitattributes
gchq/Palisade-examples pull request #90
Opened 2021-06-01 14:02 UTC by pd104923

- Added gitattributes file
- All script files have been updated to be executable
- All files have been normalised based on the new git configs so line endings have changed for some of them.
- All Dockerfiles have had any `sed` operations removed

2021-06-01 19:51 UTC, m78233 requested changes
Something odd with the shell files in the folder k8s-bash-scripts.  In github they are all tagged as empty files.  I look at them in my IDE, I can see the script.  I compare them to previous version and the message comes back that they are identical.  Could you have a close look at these in your environment?  See if you are having the same problem.

2021-06-02 07:07 UTC, pd104923 commented
This is not really an issue. I think they were marked as empty files in GitHub due to them being marked as executable. If you're seeing the script in the IDE and GitHub says they are the same then it's fine.

2021-06-02 11:53 UTC, developer01189998819991197253 requested changes
A lot of files dont have any content changes, just line endings, please refactor this PR

2021-06-02 12:54 UTC, pd104923 commented
> A lot of files dont have any content changes, just line endings, please refactor this PR

This is due to the changes that were made for this ticket. When doing a `git add --renormalize .` for the repo these files had their line endings updated.

2021-06-02 15:43 UTC, developer01189998819991197253 requested changes
Update licenses in hadolint.yaml and .gitignore also

2021-06-02 15:43 UTC, developer01189998819991197253 commented on .gitattributes
> +# Set the default behavior, in case people don't have core.autocrlf set
add palisade license header

2021-06-03 09:16 UTC, developer01189998819991197253 approved these changes

2021-06-03 09:40 UTC, merged