Pal 1063 performance tests fixes
gchq/Palisade-examples pull request #92
Opened 2021-06-04 09:14 UTC by dev930018

Awaiting merge of PAL-1025

2021-06-10 12:30 UTC, developer01189998819991197253 submitted a review, later dismissed

2021-06-11 12:33 UTC, ac74475 commented
The instructions for an automated deployment of the performance tests do not work as I dont think the service manager deploys the required kafka and redis. Therefore the documentation needs updating to get the user to run the docker compose first to start those services.

2021-06-11 12:34 UTC, ac74475 commented
Can we also remove all the legacy performance test results from the performance modules readme and make it clear that the sample results are from a single laptop deployment

2021-06-15 12:14 UTC, developer01189998819991197253 requested changes

2021-06-15 12:14 UTC, developer01189998819991197253 commented on deployment/values.yaml
> +      logging.level.root: ERROR
do we want to leave debug logging in?

2021-06-15 14:06 UTC, ac74475 commented on deployment/values.yaml
> -
this is required

2021-06-16 14:18 UTC, developer01189998819991197253 submitted a review, later dismissed

2021-06-17 11:05 UTC, ac74475 commented on deployment/values.yaml
> +      logging.level.root: ERROR
probably not as default

2021-06-17 11:07 UTC, ac74475 requested changes
see comment

2021-06-21 10:15 UTC, developer01189998819991197253 approved these changes

2021-06-22 15:57 UTC, ac74475 submitted a review, later dismissed

2021-06-23 15:11 UTC, merged