PAL-1059 initial move of files from deployment to deployment-k8s
gchq/Palisade-examples pull request #96
Opened 2021-06-11 11:50 UTC by developer01189998819991197253

2021-06-16 10:00 UTC, pd104923 requested changes
A few comments and questions

2021-06-16 12:24 UTC, developer01189998819991197253 commented on deployment-k8s/local-k8s/performance/runK8sPerformanceTest.sh
> +  kubectl exec "$(kubectl get pods --namespace="$NAMESPACE" | awk '/performance/ {print $1}')" --namespace="$NAMESPACE" -- bash -c "cd /usr/share/performance && bash ./runK8sPerformanceTest.sh"
its genrally a shell reccomendation, prevents word splitting, bit can be taken or left

2021-06-21 15:15 UTC, pd104923 requested changes
Just createHRData.sh that is not exectuable now

2021-06-21 15:33 UTC, pd104923 approved these changes

2021-06-22 09:06 UTC, dev930018 requested changes

2021-06-22 09:06 UTC, dev930018 commented on deployment-k8s/src/main/resources/k8s-bash-scripts/copyExampleData.sh
>  echo "Removed previous run classpath-jars for $CLASSPATH"
Check the mode on this file, it's been changed from 755 to 644 (no execute bit set)

2021-06-22 09:27 UTC, developer01189998819991197253 commented on deployment-k8s/Dockerfile
> +LABEL service="deployment-k8s" project="palisade"
it was just a consistency thing

2021-06-23 15:49 UTC, dev930018 approved these changes

2021-06-24 10:09 UTC, merged